monitoring-stack:
  namespaceOverride: "monitoring"
  grafana:
    namespaceOverride: "monitoring"
  kube-state-metrics:
    namespaceOverride: "monitoring"
  prometheus-node-exporter:
    namespaceOverride: "monitoring"