apiVersion: v1
kind: Service
metadata:
  name: lb-dns-tcp
  namespace: {{ .Values.namespaces.dnsNamespace }}
spec:
  selector:
    app: pihole 
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
