apiVersion: v1
kind: Service
metadata:
  name: lb-dns-udp
  namespace: {{ .Values.namespaces.dnsNamespace }}
spec:
  selector:
    app: pihole 
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer
