apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: {{ .Values.namespaces.dnsNamespace }}
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole@sha256:cb80e1086628c3db7073b65547c1869c448e1b81d60d6df7c716f3f3c6a388b5
        ports:
        - containerPort: 80
        - containerPort: 53
        - containerPort: 67
        env:
        - name: TZ
          value: Asia/Kolkata
        - name: WEBPASSWORD
          value: nice
        - name: VIRTUAL_HOST
          value: "turtle.lan"
        - name: PROXY_LOCATION
          value: "turtle.lan" 
        - name: ServerIP
          value: "127.0.0.1"
        - name: PIHOLE_DNS_
          value: "1.1.1.1;1.1.1.2"
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole
        - mountPath: /etc/dnsmasq.d
          name: dnsmasq
      volumes:
      - name: pihole
        hostPath:
          path: {{ .Values.dataDirectory }}/pihole
          type: DirectoryOrCreate
      - name: dnsmasq
        hostPath:
          path: {{ .Values.dataDirectory }}/dnsmasq.d
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: {{ .Values.namespaces.dnsNamespace }}
spec:
  selector:
    app: pihole
  ports:
  - name: tcp80
    protocol: TCP
    port: 80
    targetPort: 80
  - protocol: UDP
    port: 53
    targetPort: 53
    name: udp53
  - protocol: TCP
    port: 53
    targetPort: 53
    name: tcp53
  - protocol: UDP
    port: 67
    targetPort: 67
    name: udp67